development:
  adapter: postgresql
  database: homy_dev
  username: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5
  timeout: 5000
  port: 5432
production:
  adapter: postgresql
  database: homy_dev
  username: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5
  timeout: 5000
  port: 5432