application_name: MyApp
application_version: 1.0.0
client_id: '580360583626-gvt96nnd5gc2foblkq0mchfbqc18p37s.apps.googleusercontent.com'
client_secret: 'uPEvHuaqDQZMMjIOusMQbj9K'
access_token: 'ya29.Ci9NA3mP0hicJhwKdHmBMSQrHn7Mm_2LLo1HklAKTbnR8Bvy9eRlA0OS6OSBa7zvXQ'
refresh_token: '1/xV5e2OoCOhRnJeWFJhc_fmA9LURsz7i0Gfm2BcuYtH4'
